In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [7]:
data = pd.read_csv(r"C:\Users\yoges\OneDrive\Documents\Programming\Road-Accidents-in-India-\Data Used\indian_accidents.csv")

In [8]:
data

,Accident_Index,1st_Road_Class,1st_Road_Number,2nd_Road_Class,2nd_Road_Number,Accident_Severity,Carriageway_Hazards,Date,Day_of_Week,Did_Police_Officer_Attend_Scene_of_Accident,...,Skidding_and_Overturning,Towing_and_Articulation,Vehicle_Leaving_Carriageway,Vehicle_Location.Restricted_Lane,Vehicle_Manoeuvre,Vehicle_Reference,Vehicle_Type,Was_Vehicle_Left_Hand_Drive,X1st_Point_of_Impact,Year
0,200754AM08507,A,345,NaN,0.0,Fatal,NaN,28-01-2021,Tuesday,1,...,Skidded,No tow/articulation,Offside,0,Overtaking moving vehicle - offside,1,Car,No,Back,2021
1,2009559D02192,A,30,NaN,0.0,Fatal,NaN,29-11-2021,Thursday,1,...,NaN,No tow/articulation,Offside,0,Going ahead left-hand bend,1,Motorcycle over 500cc,No,Front,2020
2,201054MB04210,Motorway,4,NaN,0.0,Fatal,NaN,15-03-2021,Saturday,1,...,NaN,No tow/articulation,Did not leave carriageway,0,Going ahead other,2,Motorcycle over 125cc and up to 500cc,No,Back,2019
3,201014A194610,Motorway,18,A,630.0,Fatal,NaN,08-07-2020,Tuesday,1,...,NaN,No tow/articulation,Did not leave carriageway,0,Reversing,3,Other vehicle,No,Back,2019
4,201014A194610,Motorway,18,A,630.0,Fatal,NaN,30-11-2010,Tuesday,1,...,NaN,No tow/articulation,Did not leave carriageway,0,Reversing,3,Other vehicle,No,Back,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25996,201004AN10069,A,587,Unclassified,0.0,Slight,NaN,11-06-2010,Friday,1,...,NaN,No tow/articulation,Did not leave carriageway,0,Turning right,3,Car,No,Back,2010
25997,201004BA10191,Unclassified,0,Unclassified,0.0,Slight,NaN,12-11-2010,Friday,1,...,NaN,No tow/articulation,Nearside,0,Going ahead right-hand bend,1,Car,No,Front,2010
25998,201004BC10188,B,5412,A,585.0,Slight,NaN,24-08-2010,Tuesday,1,...,NaN,No tow/articulation,Did not leave carriageway,0,Moving off,2,Car,No,Back,2010
25999,201004CL10014,A,582,B,5253.0,Slight,NaN,08-02-2010,Monday,1,...,NaN,No tow/articulation,Did not leave carriageway,0,Waiting to go - held up,1,Van / Goods 3.5 tonnes mgw or under,No,Front,2010
26000,201005AA03365,A,5139,NaN,0.0,Slight,NaN,20-05-2010,Thursday,1,...,NaN,No tow/articulation,Did not leave carriageway,0,Going ahead other,2,Van / Goods 3.5 tonnes mgw or under,No,Back,2010

In [12]:
data.columns

Index(['Accident_Index', '1st_Road_Class', '1st_Road_Number', '2nd_Road_Class',
       '2nd_Road_Number', 'Accident_Severity', 'Carriageway_Hazards', 'Date',
       'Day_of_Week', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'Junction_Control', 'Junction_Detail', 'Latitude', 'Light_Conditions',
       'Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude',
       'LSOA_of_Accident_Location', 'Number_of_Casualties',
       'Number_of_Vehicles', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Road_Surface_Conditions',
       'Road_Type', 'Special_Conditions_at_Site', 'Speed_limit', 'Time',
       'Urban_or_Rural_Area', 'Weather_Conditions', 'InScotland',
       'Age_Band_of_Driver', 'Age_of_Vehicle', 'Driver_Home_Area_Type',
       'Driver_IMD_Decile', 'Engine_Capacity_.CC.',
       'Hit_Object_in_Carriageway', 'Hit_Object_off_Carriageway',
       'Journey_Purpose_of_Driver', 'Junction_Location', 'make', 'model',
       'Propulsion_Code', 'Sex_of_Driver', 'Skidding_and_Overturning',
       'Towing_and_Articulation', 'Vehicle_Leaving_Carriageway',
       'Vehicle_Location.Restricted_Lane', 'Vehicle_Manoeuvre',
       'Vehicle_Reference', 'Vehicle_Type', 'Was_Vehicle_Left_Hand_Drive',
       'X1st_Point_of_Impact', 'Year'],
      dtype='object')

In [14]:
data.isnull().sum()

Accident_Index                                     0
1st_Road_Class                                     0
1st_Road_Number                                    0
2nd_Road_Class                                 11419
2nd_Road_Number                                  290
Accident_Severity                                  0
Carriageway_Hazards                            25443
Date                                               0
Day_of_Week                                        0
Did_Police_Officer_Attend_Scene_of_Accident        0
Junction_Control                                   0
Junction_Detail                                    0
Latitude                                           0
Light_Conditions                                   0
Location_Easting_OSGR                              0
Location_Northing_OSGR                             0
Longitude                                          0
LSOA_of_Accident_Location                        493
Number_of_Casualties                               0
Number_of_Vehicles                                 0
Pedestrian_Crossing-Human_Control                  0
Pedestrian_Crossing-Physical_Facilities            0
Road_Surface_Conditions                            0
Road_Type                                          0
Special_Conditions_at_Site                     25268
Speed_limit                                        0
Time                                               0
Urban_or_Rural_Area                                0
Weather_Conditions                                 0
InScotland                                         0
Age_Band_of_Driver                                 0
Age_of_Vehicle                                     0
Driver_Home_Area_Type                              0
Driver_IMD_Decile                               3165
Engine_Capacity_.CC.                             132
Hit_Object_in_Carriageway                      24070
Hit_Object_off_Carriageway                     21496
Journey_Purpose_of_Driver                          0
Junction_Location                                  0
make                                            5537
model                                           2067
Propulsion_Code                                    0
Sex_of_Driver                                      0
Skidding_and_Overturning                       19441
Towing_and_Articulation                            0
Vehicle_Leaving_Carriageway                        0
Vehicle_Location.Restricted_Lane                   0
Vehicle_Manoeuvre                                  0
Vehicle_Reference                                  0
Vehicle_Type                                       0
Was_Vehicle_Left_Hand_Drive                        0
X1st_Point_of_Impact                               0
Year                                               0
dtype: int64

In [16]:
data.shape

(26001, 53)

In [17]:
data.describe(include='all')

,Accident_Index,1st_Road_Class,1st_Road_Number,2nd_Road_Class,2nd_Road_Number,Accident_Severity,Carriageway_Hazards,Date,Day_of_Week,Did_Police_Officer_Attend_Scene_of_Accident,...,Skidding_and_Overturning,Towing_and_Articulation,Vehicle_Leaving_Carriageway,Vehicle_Location.Restricted_Lane,Vehicle_Manoeuvre,Vehicle_Reference,Vehicle_Type,Was_Vehicle_Left_Hand_Drive,X1st_Point_of_Impact,Year
count,26001,26001,26001.000000,14582,25711.000000,26001,558,26001,26001,26001.000000,...,6560,26001,26001,26001.000000,26001,26001.000000,26001,26001,26001,26001.000000
unique,18837,6,NaN,6,NaN,3,5,1460,7,NaN,...,5,6,9,NaN,18,NaN,13,3,6,NaN
top,201006XP26465,A,NaN,Unclassified,NaN,Slight,Any animal in carriageway (except ridden horse),12-11-2010,Friday,NaN,...,Skidded,No tow/articulation,Did not leave carriageway,NaN,Going ahead other,NaN,Car,No,Front,NaN
freq,9,12508,NaN,9895,NaN,17775,197,82,4340,NaN,...,4631,25751,20362,NaN,12552,NaN,19621,25975,14638,NaN
mean,NaN,NaN,982.875812,NaN,435.147058,NaN,NaN,NaN,NaN,1.093843,...,NaN,NaN,NaN,0.077497,NaN,1.441021,NaN,NaN,NaN,2014.482405
std,NaN,NaN,1789.917052,NaN,1446.424444,NaN,NaN,NaN,NaN,0.295545,...,NaN,NaN,NaN,0.749432,NaN,0.719022,NaN,NaN,NaN,4.929699
min,NaN,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,1.000000,...,NaN,NaN,NaN,0.000000,NaN,1.000000,NaN,NaN,NaN,2010.000000
25%,NaN,NaN,4.000000,NaN,0.000000,NaN,NaN,NaN,NaN,1.000000,...,NaN,NaN,NaN,0.000000,NaN,1.000000,NaN,NaN,NaN,2010.000000
50%,NaN,NaN,158.000000,NaN,0.000000,NaN,NaN,NaN,NaN,1.000000,...,NaN,NaN,NaN,0.000000,NaN,1.000000,NaN,NaN,NaN,2010.000000
75%,NaN,NaN,684.000000,NaN,0.000000,NaN,NaN,NaN,NaN,1.000000,...,NaN,NaN,NaN,0.000000,NaN,2.000000,NaN,NaN,NaN,2020.000000
max,NaN,NaN,9999.000000,NaN,9999.000000,NaN,NaN,NaN,NaN,3.000000,...,NaN,NaN,NaN,9.000000,NaN,17.000000,NaN,NaN,NaN,2021.000000

In [19]:
data.columns

Index(['Accident_Index', '1st_Road_Class', '1st_Road_Number', '2nd_Road_Class',
       '2nd_Road_Number', 'Accident_Severity', 'Carriageway_Hazards', 'Date',
       'Day_of_Week', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'Junction_Control', 'Junction_Detail', 'Latitude', 'Light_Conditions',
       'Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude',
       'LSOA_of_Accident_Location', 'Number_of_Casualties',
       'Number_of_Vehicles', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Road_Surface_Conditions',
       'Road_Type', 'Special_Conditions_at_Site', 'Speed_limit', 'Time',
       'Urban_or_Rural_Area', 'Weather_Conditions', 'InScotland',
       'Age_Band_of_Driver', 'Age_of_Vehicle', 'Driver_Home_Area_Type',
       'Driver_IMD_Decile', 'Engine_Capacity_.CC.',
       'Hit_Object_in_Carriageway', 'Hit_Object_off_Carriageway',
       'Journey_Purpose_of_Driver', 'Junction_Location', 'make', 'model',
       'Propulsion_Code', 'Sex_of_Driver', 'Skidding_and_Overturning',
       'Towing_and_Articulation', 'Vehicle_Leaving_Carriageway',
       'Vehicle_Location.Restricted_Lane', 'Vehicle_Manoeuvre',
       'Vehicle_Reference', 'Vehicle_Type', 'Was_Vehicle_Left_Hand_Drive',
       'X1st_Point_of_Impact', 'Year'],
      dtype='object')

In [25]:
data.drop(['Location_Easting_OSGR','Location_Northing_OSGR'],axis = 1 ,inplace= True)

In [27]:
data.shape

(26001, 51)

In [ ]:
df.col